### ISSUE TITLE
XLSX parsing crashes on gradient-filled cells: `'GradientFill' object has no attribute 'patternType'`

### ISSUE THREAD

**Issue by jakob-at-brixl** [myhloli/DocVortex#4]
Hi myhloli, while working with MinerU 3.4.5 and the new MinerU 4.x.x versions I noticed that gradient filled cells make a spreadsheets fail. 

=== text below is AI generated but verified by me === 

One cell with a gradient fill (Excel: Format Cells > Fill > Fill Effects) makes the whole workbook fail. The style extraction assumes every fill is an openpyxl `PatternFill`:

`src/docvortex/analyzers/native/office/spreadsheet/projector.py`, line 711 (0.4.15 and current `main`)

```python
if cell.fill and cell.fill.patternType == "solid" and cell.fill.fgColor:
```

openpyxl returns a `GradientFill` for such cells, which has no `patternType`.

**Reproduce**

```python
from io import BytesIO

from docvortex.analyzers.native import XlsxModel
from openpyxl import Workbook
from openpyxl.styles import GradientFill

workbook = Workbook()
sheet = workbook.active
sheet["A1"] = 240
sheet["A1"].fill = GradientFill(stop=("FFFFFF", "99CCFF"))
buffer = BytesIO()
workbook.save(buffer)
XlsxModel().predict(BytesIO(buffer.getvalue()))
# AttributeError: 'GradientFill' object has no attribute 'patternType'
```

Without the `GradientFill` line the workbook parses. Found in a real-world workbook; openpyxl 3.1.5 loads it fine.

**Suggested fix**

```python
fill = cell.fill
if getattr(fill, "patternType", None) == "solid" and fill.fgColor:
```

**This also affects MinerU,**

- MinerU 4.x parses XLSX through DocVortex and does not catch the error, so MinerU 4.0.3
  fails on these workbooks. A DocVortex release with the fix resolves it there.
- MinerU 3.4.5 carries its own copy of the same line in `mineru/model/xlsx/xlsx_converter.py`, line 1586 (`_extract_cell_style`), and needs the same fix in a 3.4.x release.

Environment: DocVortex 0.4.15, openpyxl 3.1.5, Python 3.12, Linux and macOS.

**Comment by myhloli** [comment]
Thanks for the clear report and the precise analysis — the suggested fix is exactly what landed.

Fixed in [v0.4.18](https://github.com/myhloli/DocVortex/releases/tag/v0.4.18) (commit 3429f9d): `SpreadsheetProjector._extract_cell_style` now reads the fill via `getattr(fill, "patternType", None) == "solid"`, so a `GradientFill` no longer raises. Gradient-filled cells keep their content and all other supported styles; only the solid background color is extracted, as before.

Regression tests were added in `tests/unittest/test_flash_spreadsheet_projector.py`, covering mixed `PatternFill`/`GradientFill` workbooks (including your repro shape).

For MinerU 4.x users, upgrading `docvortex` to `>= 0.4.18` (already on PyPI) resolves it. The 3.4.x copy in `mineru/model/xlsx/xlsx_converter.py` needs a separate fix on the MinerU side.
